apiVersion: v1
kind: Secret

metadata:
  name: back-secrets
  namespace: transdoo-ns

type: Opaque

stringData:
  DB_NAME: "transdoo"
  DB_PASSWORD: "transdoo123"
  JWT_REFRESH_SECRET: "this-is-a-personal-token-for-jwt-refresh-secret"
  JWT_ACCESS_SECRET: "this-is-a-personal-token-for-jwt-access-secret"
  CORS_ORIGIN: "http://54.206.214.242:3000"
