apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - db/statefulset.yml
  - db/service.yml
